-- Create a table for the gallery memories
create table memories (
  id bigint generated by default as identity primary key,
  image_url text not null,
  date text,
  caption text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For this private app, we will allow anonymous reads and inserts
-- Note: In a production app with users, you would restrict this further.
alter table memories enable row level security;

create policy "Enable read access for all users"
on memories for select
using (true);

create policy "Enable insert for everyone (protected by client passcode)"
on memories for insert
with check (true);

create policy "Enable update for everyone"
on memories for update
using (true);

-- Create a storage bucket for images
-- You will need to create a bucket named 'gallery-images' in the Supabase Dashboard > Storage
-- ensuring it is set to "Public" so images can be viewed.
