-- 1. Create a table for the gallery memories
create table if not exists memories (
  id bigint generated by default as identity primary key,
  image_url text not null,
  date text,
  caption text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Set up RLS for the memories table
alter table memories enable row level security;

-- Drop existing policies to ensure clean state
drop policy if exists "Enable read access for all users" on memories;
drop policy if exists "Enable insert for everyone" on memories;
drop policy if exists "Enable update for everyone" on memories;

create policy "Enable read access for all users"
on memories for select
using (true);

create policy "Enable insert for everyone"
on memories for insert
with check (true);

create policy "Enable update for everyone"
on memories for update
using (true);

-- 3. Create the Storage Bucket ('gallery-images') via SQL
-- Note: This is usually done in the UI, but we can do it here too!
insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do nothing;

-- 4. Set up Storage Policies (IMPORTANT!)
-- Drop existing policies to avoid conflicts
drop policy if exists "Public Access" on storage.objects;
drop policy if exists "Public Upload" on storage.objects;

-- Allow public access to view images
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'gallery-images' );

-- Allow anyone to upload (since we gate it via passcode on frontend)
create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'gallery-images' );

-- Allow updates too (optional but good for overwrites)
create policy "Public Update"
on storage.objects for update
using ( bucket_id = 'gallery-images' );
